services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    expose:
      - "80"
    ports:
      - "80"
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      MONGO_URL: ${MONGO_URL}
      DB_NAME: ${DB_NAME:-sales_order_db}
    restart: unless-stopped
